# Generated by Django 3.0.7 on 2020-06-11 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='seen',
            field=models.IntegerField(default='00000', editable=False, max_length=5),
        ),
    ]
