# Generated by Django 3.0.7 on 2020-06-17 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20200611_1119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='source',
            new_name='contenttype',
        ),
    ]
