# Generated by Django 3.0.7 on 2020-06-18 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='description',
            new_name='quoone',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='contenttype',
            new_name='quothree',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='mentor',
            new_name='quotwo',
        ),
    ]
