# Generated by Django 3.0.7 on 2020-06-11 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brainplatform', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tweet',
        ),
    ]
